source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Tayphoon/TayphoonSpecs.git'

platform :ios, '8.0'

target 'TCViperModuleTransitions' do
  pod 'TCViperModuleTransitions', '~> 0.1.0'
end
